# Generated by Django 5.2.7 on 2026-01-07 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('skills', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('competences', models.TextField(help_text='Compétences séparées par des virgules')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('salaire', models.CharField(max_length=50)),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postulation', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField(blank=True, null=True)),
                ('found_skills_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECUE', 'Reçue'), ('QUALIFIEE', 'Qualifiée'), ('ENTRETIEN', 'Entretien'), ('REFUSEE', 'Refusée')], default='RECUE', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to='pages.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to='pages.offre')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('VISIO', 'Visio'), ('PRESENTIEL', 'Présentiel')], default='VISIO', max_length=20)),
                ('link_or_address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('postulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entretien', to='pages.postulation')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('candidat', 'Candidat'), ('recruteur', 'Recruteur')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='postulation',
            index=models.Index(fields=['offre', 'status'], name='pages_postu_offre_i_d2bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='postulation',
            index=models.Index(fields=['score'], name='pages_postu_score_d7759d_idx'),
        ),
        migrations.AddConstraint(
            model_name='postulation',
            constraint=models.UniqueConstraint(fields=('candidat', 'offre'), name='uniq_postulation_candidat_offre'),
        ),
    ]
