"""
Django settings for helloword project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # Nécessaire pour gérer les chemins des fichiers médias

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eds$qxpx-&tu3$n+a_u+d+s-6&@l5t24zmxdg(^k^r(u14emox'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] # Ajouté pour le développement local


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "pages",  # Votre application principale
    'meeting', # L'application qui causait l'avertissement
]

# NOTE SUR L'AVERTISSEMENT "meeting.meeting":
# L'erreur "RuntimeWarning: Model 'meeting.meeting' was already registered" peut se produire
# si l'application 'meeting' est listée dans INSTALLED_APPS mais qu'elle n'est pas configurée
# correctement. Assurez-vous qu'il n'y a pas de doublon dans la définition des modèles
# de cette application. Si vous n'utilisez pas 'meeting', vous pouvez la commenter.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'helloword.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], # Assurez-vous que ce dossier existe pour vos templates globaux
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Indispensable pour que MEDIA_URL soit accessible dans les templates
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'helloword.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Redirections après authentification
LOGIN_REDIRECT_URL = 'home'  # Redirige vers la page d'accueil après connexion
LOGOUT_REDIRECT_URL = 'login' # Redirige vers la page de login après déconnexion
LOGIN_URL = 'login'          # URL de la page de login si l'utilisateur n'est pas connecté


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Configuration des emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tassnim.marzougui@isimg.tn'
EMAIL_HOST_PASSWORD = 'dufh vtin mwrt ycqe'
DEFAULT_FROM_EMAIL = 'noreply@khademny.com'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"] # Dossier pour vos fichiers statiques (CSS, JS, images)

# Fichiers médias (CV uploadés par les candidats)
# C'est crucial pour que les CV soient sauvegardés et accessibles
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Le dossier 'media' sera créé à la racine de votre projet

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuration Jazzmin (pour l'interface d'administration)
JAZZMIN_SETTINGS = {
    "site_title": "Khademny Admin",
    "site_header": "Khademny",
    "site_brand": "Khademny",
    "welcome_sign": "Bienvenue dans l'administration Khademny",
    "copyright": "Khademny © 2024",
}